# DVC Parameters Configuration
# These parameters are tracked by DVC and used in the pipeline

backtester:
  # Stock universe to test
  universe:
    - NVDA
    - AAPL
    - MSFT
    - TSLA
    - AMD
    - META
    - GOOGL
  
  # Historical data range
  start_date: "2024-01-01"
  
  # Grid search parameters
  lookback_windows:
    - 10
    - 20
    - 30
  
  holding_periods:
    - 5
    - 10
    - 15
  
  # Initial capital
  initial_capital: 10000

scanner:
  # Lookback window (update from backtest results)
  lookback_window: 20
  
  # Number of top picks to return
  top_n: 10
  
  # Minimum R² threshold
  min_r2: 0.8
  
  # Finviz filters
  min_price: 5.0
  min_volume: 500000

# Data sources
data:
  # Preferred data source (fd or yfinance)
  primary_source: "fd"
  
  # Cache settings
  cache_enabled: true
  cache_ttl_days: 1
